morph/main.py
This makes it much easier to iteratively tweak config settings
and see the results.
In the glorious future all of this config will be in jcfg rather than
in code (see #6), which will solve this problem comprehensively.
=> Reload config before rebuilding db

mm, morph/cli.py, morph/mm
This comes in handy on its own, for pulling out data from MorphMan in
a form that's easy to use one's favorite general-purpose text tools
for reading, searching, comparing against other data, etc.
It also provides a skeleton for further CLI commands that do more
interesting things.
=> cli: one simple working command, to dump a MorphMan database

morph/morphemizer.py
This came out of some time spent studying how MorphMan starts its
`mecab` subprocess, and studying MeCab itself, in order to reproduce
the same `mecab` output outside the context of a full running Anki
application.  Hopefully it will be helpful for the next person.
One stumbling block I'd hit is that MeCab can work with a variety of
dictionaries (in fact this is something the MeCab upstream is very
proud of!), and the `mecab` I'd originally gotten on my system outside
of the Japanese Support addon was using a different dictionary
(jumandic) from the one bundled in that addon (ipadic), but our
`mecab` command line embeds specific assumptions about the dictionary.
The new `bos-feature` check catches that issue.  Handily `mecab -P`
provides both that information and the charset information …
=> Refactor how we start mecab, and add more comments and checks

morph/newMorphHelper.py
This _appears_ to fix landonepps#6 
I also made a _tiny_ refactor of `skipConditions`, because readability
=> Fix scheduler v2

__init__.py
Groups all MorphMan menu entries in a single Submenu of Tools menu.
=> Group all MorphMan menu entries in a submenu

morph/newMorphHelper.py
frequency_list has to be initialized or it will crash in line 276 (now 277)
=> Initialize frequency_list if no frequency.txt

morph/main.py, morph/preferencesDialog.py, morph/util.py
=> Add field for focus morph part of speech

morph/main.py
I got rid of any instance where the focus field is cleared to attempt to fix #45 .
=> Stop clearing the focus field altogether

morph/morphemizer.py, test/test_space_morphemizer.py
Fixes #55. I added the suggested regex and all of the test cases continued to pass.
=> Improve SpaceMorphemizer parser; add SpaceMorphemizer test cases

test/test_preferences.py
Add test for **update_preferences** method
=> Add test for update_preferences method

morph/morphemizer.py, morph/preferencesDialog.py, morph/readability.py
In Readability Analyzer Dialog, the default morphemizer is saved in the profile preferences whenever the ComboBox changes value.
=> readability analyzer save default morphemizer

test/test_preferences.py
Normalize expected the path for Windows.
=> fix 77: Fix path expectation on Windows.

__init__.py, morph/browser/boldUnknowns.py
=> Add browser feature to bold any unknown morphs in fields.

morph/stats.py
This fixes the toolbar issue for me under Windows.
=> Fix toolbar links init changes introduced in Anki 2.1.22 (#97)

scripts/dumb_db.py
I have removed unnecessary code. It simply dumps a .db file as a tab-delimited csv file.
=> Added a script to dump a database from the command line.

morph/browser/batchPlay.py
Batch Play feature doesn't work in 2.1.26, this fixes it
=> Fixes batch play feature in Anki 2.1.26

morph/morphemes.py, test/test_ignore_brackets_morphemizer.py
- Changes rounded brackets regex to include both English and Japanese brackets
- Adds tests
=> Ignore brackets to support both English/Japanese brackets

morph/main.py
These changes speed up processing significantly. In my computer it goes from 24 seconds to 9 seconds.
=> Update processing of notes to avoid inspecting every single note

morph/config.py, morph/main.py, morph/preferences.py, morph/preferencesDialog.py
Cards (not notes) that are suspended and are leeches will be ignored. If all the cards of a note are suspended and leeches, the note will be ignored.
=> Add option to ignore suspended leeches

morph/main.py
Simple fix for https://github.com/landonepps/MorphMan21/issues/62
=> Catches `IndexError` to prevent crash.

.github/workflows/build.yml, README.md, morph/graphs.py, morph/main.py, morph/mecab_wrapper.py, morph/morphemizer.py, morph/newMorphHelper.py, morph/readability.py
Fix #261: Prevent error when handling syntax formatting in focus fields.
Improved Mecab's perse caching performance.
Other minor fixes.
=> Several updates for 2022.2
