kaegi/MorphMan

- morph/preferencesDialog.py
I noticed that, when trying to set 'All note types' in the Note Filter
dialog, it would always jump back to the first *actual* note type
upon reloading the dialog. The data was saved correctly into the json
config, however. Turns out it was just a simple +1 error. :)
> Fix wrong note in GUI when reading from config

- morph/extractMorphemes.py
- morph/massTagger.py
- morph/viewMorphemes.py
Three of the commands in the browser window were still using the old
location for the MorphMan fields (`morph_fields` from `cfg()`). This
commit changes those commands to use the filters in `jcfg()` instead.
It also fixes the errors occuring `massTagger.per()` and
`viewMorphemes.per()` for the case where no notes in the current
selection were in the DB/had correct filters in `jcfg()`.
> Fix cfg() instead of jcfg() for field usage

- morph/util.py
This uses a dict in Anki's `mw.col.conf` dict for storing MorphMan
jcfg data, which makes the JSON handling unneccessary. The
Anki addon writing guide states that small config data (and I 
would argue the jcfg config data is fairly small) can be stored
in the `conf` dict.
The config data resides in `mw.col.conf['addons']['morphman']`. If the
`addons` dict does not yet exist, it will be created during
`initJcfg()`. I have chosen an `addon` subdict because I think it makes
sense to store addon data in a namespace separate from the 'regular'
Anki config data.
As far as I can tell, this change requires a one-time full sync to function
reliably, otherwise the local `mw.col.conf` dict will be overwritten with
the server-side one for some reason. After a full sync, it works
flawlessly for me.
I …
> Use Anki's internal conf dict for storing jcfg

- morph/preferencesDialog.py
This line triggered the assertion in `setTableRow()` when trying to move
the first table row upwards.
> Fix +1 error in moveRowUp()

- morph/config.py
- morph/main.py
Rather than name an "optimal" length L but treat all lengths [L-2,L+2]
as equally optimal, just name explicitly the min and max lengths for
that interval of equally-good lengths.
And fix the logic of the `mm_tooLong` tag to match how we prioritize
notes, only applying to notes we're actually penalizing for their
length rather than notes longer than the midpoint of the optimal
interval but which may still be within it.
Also widen the optimal interval somewhat by default,
from [2,6] to [2,8], because 6 morphemes is pretty short.
> Sentence lengths: more explicit and flexible config

- morph/main.py
These spit out a fair amount of noise each time I recalculate for the
day -- at least the `.mats` one does, because it's triggered by all
the cards I've reviewed.  They're debugging output that could be
useful in active development but are pure noise for a user; I had no
idea what they might be trying to tell me, up until just the other day
when I'd started trying some development on MorphMan and was looking
at this very piece of code.
So comment them out, just like the `.loc` print above them.
Alternatively it'd be pretty reasonable to delete them entirely.
> Silence some noisy prints

- morph/main.py
- morph/morphemes.py
- morph/stats.py
This allows us to introduce external data that a given morpheme
is common, based on some external corpus, without needing to
record 1000 separate locations to get a frequency of 1000.
In looking for code that does the simple `len(locs)` frequency
count and should be updated to call the new function, found a
method that looks to be dead code (`popDb`) and a computation --
the "Calculating frequency information" step familiar from the
MorphMan recalc progress-bar dialog -- whose results are
apparently never used!  So cut both of those.
Also introduce a new Corpus location type, convenient for
this form of usage.
> Extend locations to optionally carry weights used in frequency

- morph/main.py
- morph/preferencesDialog.py
- morph/util.py
This makes the tags on too-short and too-long texts much more
symmetrical and easy to describe, and provides all the same
information to filter on.  It also gets rid of the "bad length" name,
which isn't particularly clear about what it means and sounds a lot
like an error message, in favor of the very straightforward
descriptions "too short" and "too long".
> Remove `mm_badLength` tag, replace with `mm_tooShort`

- morph/main.py
When specifying a float number in config.py 'frequency.txt weight scale' property, for example, 
0.5 as recomended in [MIA](https://massimmersionapproach.com/table-of-contents/anki/morphman/#frequency) website. Then the calculated **due** contains decimals.
This PR converts the usefulness to a rounded int before using it for the mmi.
> Convert usefulness to integer

- morph/config.py
- morph/main.py
Use the already calculated frequencyListLength to simplify the use of a frequency.txt file.
With this PR there is no need to change config.py to match the length of the frequency.txt file.
> Automatically use the length of frequency.txt to create a bonus

- .pylintrc
- __init__.py
- morph/browser/extractMorphemes.py
- morph/cli.py
- morph/main.py
- morph/manager.py
- morph/morphemes.py
- morph/newMorphHelper.py
- morph/readability.py
- morph/util.py
This PR adds a PyLint configuration. The configuration has been copied and adapted from Anki's.
It fixes the following errors and warnings:
-------------------------------------------------------------------
************* Module MorphMan
__init__.py:71:4: W0611: Unused viewMorphemes imported from morph.browser (unused-import)
__init__.py:72:4: W0611: Unused extractMorphemes imported from morph.browser (unused-import)
__init__.py:73:4: W0611: Unused batchPlay imported from morph.browser (unused-import)
__init__.py:74:4: W0611: Unused massTagger imported from morph.browser (unused-import)
__init__.py:75:4: W0611: Unused learnNow imported from morph.browser (unused-import)
__init__.py:76:4: W0611: Unused browseMorph imported from morph.browser (unused-import)
__init__.py:77:4: W0611: Unused …
> add pylint and fix or disable errors

- README.md
- morph/UI/__init__.py
- morph/UI/morphemizerComboBox.py
- morph/manager.py
- morph/preferencesDialog.py
- morph/readability.py
- morph/readability.ui
- morph/readability_ui.py
- scripts/build_ui.py
- test/test_MorphemizerComboBox.py
There are 4 places where a combo box is used to select the Morphemizer.
I have created a custom Qt Widget **MorphemizerComboBox** and replaced all duplicated code.
Because the custom widget is in a relative path, we must modify the file produced by **pyuic5**. Therefore I have created a build script that can be used for any future UI file or custom widget.
Finally I have updated README to clarify development.
> extract MorphemizerComboBox

- morph/mecab_wrapper.py
- morph/morphemizer.py
About #74 
This somehow fixes the problem by putting the condition to the morphs/deps.
It also gives a better error message if it gets to the end.
I have extracted all the messy mecab code out of the clean morphemizers.py. 
This will allow to add tests for this mecab wrapper.
> extract mecab messy code out of morphemizers and workaround issues/74

- morph/config.py
- morph/customTableWidget.py
- morph/main.py
- morph/morphemes.py
- morph/newMorphHelper.py
- morph/preferences.py
- morph/preferencesDialog.py
- morph/readability.py
- morph/readability.ui
- morph/readability_ui.py
* Moved various options to cfg so they can be saved per profile and don't require editing config.py.
* New parsing options that primarily will work for the Japanese Mecab parser:
- Option to ignore contents inside（ ）round brackets.
- Option to ignore grammar definitions.
- Option to treat proper nouns (people & place names) as already known in Japanese text.
* New "Minimum Master Frequency" option.
* New Table based UI features in Readability Analyzer.
* New morpheme score function in Readability Analyzer.
> Readability analyzer updates

- .github/workflows/build.yml
- morph/cli.py
Instead of Travis-CI we can use GitHub Actions.
This PR add configuration to run tests and pylint on a matrix of:
* 3 python versions (3.6, 3.7, 3.8)
* 3 OS (Ubuntu, Mac, Windows)
* 1 Anki version
I had to skip one pylint error only happening in Windows.
> add GitHub Workflows

- morph/morphemizer.py
Add-ons such as MIA Japanese insert spaces (ASCII code 0x20) to mark
certain boundaries.  Those spaces can lead to incorrect parsing by
Mecab.  This change strips those spaces spaces, but doesn't affect
full-width spaces that may appear normally in Japanese script.
> Ignore simple spaces in the Japanese Mecab Morphemizer.

- morph/main.py
Anki internal restructuring means that old sqlite database code doesn't work anymore (see #116).
I manually checked that this code works on Anki versions 2.1.22 and 2.1.26.
> make compatible with new DBProxy.executemany

- morph/main.py
@ianki I think this fixes a bug in your new frequency list changes, can you verify?
Currently it returns `None` which breaks the integer comparison below it
> Fixes issue in checking against frequency list during recalc

- .github/workflows/build.yml
- README.md
Anki's directory structure changed, and the `PYTHONPATH` suggestion in the `README.md` no longer works since Anki 2.1.17
My changes corrects this, plus suggests adding the root directory to `PYTHONPATH` to allow `pylint <directory>` to be able to access all libraries accessible from the root project
I've tested this with Anki 2.1.26 (stable) and access to libraries works fine. I do not been able to test against the latest stable Anki 2.1.35, as it's currently not in the Arch repos, so any help would be appreciated.
> Updates pylint config for Anki 2.1.26 (README & Github Workflow updates)

- morph/util.py
Previously when all note types was selected, it didn't match any notes.
Now it matches all notes.
> Fix all-note-types filter

- .github/workflows/build.yml
- .gitignore
We were getting warnings for using deprecated action versions
> Update build.yml to use latest actions

- morph/errors/profileNotYetLoadedException.py
- morph/preferences.py
- morph/stats.py
Handle the case where the toolbar stats are loaded before the profile.
Since Anki 2.1.50, the "top_toolbar_did_init_links" hook is triggered before the profile is loaded, which raises an error because we need the profile to be loaded to be able to retrieve the stats.
https://github.com/kaegi/MorphMan/issues/262
https://github.com/kaegi/MorphMan/issues/273
> handle toolbar stats loading in Anki 2.1.54-qt5
